#rootPath: X:\Svc\SCOPC-PRODPC\FERME04\PROD\PROD_PC\ini
#rootPath: C:\Users\LI26GX\Desktop\Ini
rootPath: C:\Users\LI26GX\Desktop\Adabas
fileNamePattern:
  names:
    - "SC"
  excludeds:
    - ""
searchPatterns:
  - "A24130."
outputName: jcl-proc-sc.csv